### ISSUE TITLE
ImportError: cannot import name TwitterBot

### ISSUE THREAD

**Issue by AJBBB** [rhiever/TwitterFollowBot#54]
Traceback (most recent call last):
  File "twitter.py", line 8, in <module>
    from TwitterFollowBot import TwitterBot
  File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 21, in <module>
    from twitter import Twitter, OAuth, TwitterHTTPError
  File "/home/ubuntu/twitter.py", line 8, in <module>
    from TwitterFollowBot import TwitterBot
ImportError: cannot import name TwitterBot

I am on an ubuntu 14.04 box, I've installed pip, TwitterFollowBot, Twitter, birdy, requests, and I get this error only on my Ubuntu 14.04 server. The script runs fine on my main PC Xubuntu 15

**Comment by rhiever** [comment]
What version are you running?

On Tue, Jul 7, 2015 at 3:32 PM, AJBBB <notifications@github.com> wrote:

> Traceback (most recent call last):
> File "twitter.py", line 8, in
> from TwitterFollowBot import TwitterBot
> File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/*init*.py",
> line 21, in
> from twitter import Twitter, OAuth, TwitterHTTPError
> File "/home/ubuntu/twitter.py", line 8, in
> from TwitterFollowBot import TwitterBot
> ImportError: cannot import name TwitterBot
>
> I am on an ubuntu 14.04 box, I've installed pip, TwitterFollowBot,
> Twitter, birdy, requests, and I get this error only on my Ubuntu 14.04
> server. The script runs fine on my main PC Xubuntu 15
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/54>.
>



-- 
Randal S. Olson, Ph.D.

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by AJBBB** [comment]
I'm sorry i'm not sure of what version you are referring too. Version of TwitterFollowBot? 

I installed it from pip install TwitterFollowBot

**Comment by AJBBB** [comment]
I've also tried cloning the github and installing from setup.py and that made no difference,

**Comment by rhiever** [comment]
I just released a new version (2.0.1) on pypi. I wonder if something funky is going on. What if you install 2.0? https://github.com/rhiever/TwitterFollowBot/releases/tag/v2.0

**Comment by AJBBB** [comment]
after uninstalling through pip, I installed 2.0 from the zip and I am still receiving the same error code:

Traceback (most recent call last):
  File "twitter.py", line 8, in <module>
    from TwitterFollowBot import TwitterBot
  File "build/bdist.linux-x86_64/egg/TwitterFollowBot/__init__.py", line 21, in <module>
  File "/home/ubuntu/twitter.py", line 8, in <module>
    from TwitterFollowBot import TwitterBot
ImportError: cannot import name TwitterBot

Again, this works on my 15.04 pc no problem. (Note: I installed TwitterFollowBot on that pc yesterday, so I'm not sure if the version change from 2.0 to 2.0.1 even had an effect.

**Comment by rhiever** [comment]
The 2.0.1 release just went out a couple hours ago.

**Comment by AJBBB** [comment]
I would assume that's not the problem then right?

**Comment by rhiever** [comment]
Seems not. I can't reproduce this error on my end, so it's a bit hard to debug. Perhaps try just importing TwitterFollowBot:

    import TwitterFollowBot

still get an error?

**Comment by AJBBB** [comment]
I added in import TwitterFollowBot and removed my from import statement.

I believe this also requires me now to use TwitterFollowBot.TwitterBot()
correct?

After doing both of those I get this:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "twitter.py", line 8, in <module>
    import TwitterFollowBot
  File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 21, in <module>
    from twitter import Twitter, OAuth, TwitterHTTPError
  File "/home/ubuntu/twitter.py", line 64, in <module>
    follow_bot = TwitterFollowBot.TwitterBot()
AttributeError: 'module' object has no attribute 'TwitterBot'

**Comment by rhiever** [comment]
That's right. So it looks like you have the bot installed and linked, but something's wrong with the install.

What's in the file `/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/init.py`?

**Comment by AJBBB** [comment]
The file /usr/local/lib/python2.7/dist-packages/TwitterFollowBot/init.py is not created /does not exist.

The file /usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py has 499 lines of code, do you want me to copy the whole thing here?

**Comment by rhiever** [comment]
Nope - but does it look like this? https://github.com/rhiever/TwitterFollowBot/blob/master/TwitterFollowBot/__init__.py

**Comment by AJBBB** [comment]
It was slightly different, starting with line 20 which didn't even exist in my __init__.py 

I replaced my __init__.py with the one you gave me and still got this error:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "twitter.py", line 8, in <module>
    import TwitterFollowBot
  File "/usr/local/lib/python2.7/dist-packages/TwitterFollowBot/__init__.py", line 17, in <module>
    from twitter import Twitter, OAuth, TwitterHTTPError
  File "/home/ubuntu/twitter.py", line 64, in <module>
    follow_bot = TwitterFollowBot.TwitterBot()
AttributeError: 'module' object has no attribute 'TwitterBot'

**Comment by AJBBB** [comment]
I'm going to email you my program so you can see if it's my code or a setup issue, I trust you won't share its details. It's a simple twitter bot that tweets and follows people. 
The email is coming from ajbbb@mail.com

**Comment by AJBBB** [comment]
I have been struggling with this for a while today, even updated to 15.04 to check if that was the issue. I'm putting this issue down to either AWS' servers, or my user error. Thanks so much for the help. I appreciate your time.

**Comment by OlivierBrunet** [comment]
AYJAYY, I have exactly the same issue.. did you manage to fix it somehow ?

**Comment by AYJAYY** [comment]
I did not. I was unable to figure it out and I decided to not use this library, 

Thanks!

Sent from myMail for iOS

Saturday, October 29, 2016, 5:21 PM -0400 from Olivier Brunet  notifications@github.com:

**Comment by OlivierBrunet** [comment]
I finally managed to solve this error by recloning the repo and renaming my twitter.py file (not sure about that one), hope this helps someone.
